<?php
define("TIME_LIMIT_RANGE","20");// in days
define("TIME_LIMIT_RANGE_FOR_REQUEST_NEW_SESSION_CODE","1");// in days
define("VERIFICATION_CODE_TIME_LIMIT", "5"); //in hours
define("DEFAULT_GENERATE_CODE","111111");

define("UNKNOWN_ERR","10000");
define("DATABASE_CONNECTION_FAILED","10054");
define("SESSION_CODE_INVALID","10055");
define("PARAMETER_NOT_VALID","10056");
define("EMAIL_SENT_FAILED","10057");
define("WRONG_VERIFICATION_CODE","10058");
define("ERR_CURL_NOT_ACTIVED","10059");
define("ERR_SMS_SENT_FAILED","10060");

?>
